#ifndef  _WIFICONFIGURATOR
#define  _WIFICONFIGURATOR

 static const char  wifiConfigurationHTML[] =   
    "<!DOCTYPE html>   \n"
    "<html>   \n"
    "<head>  \n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">  \n"
    "<title> Wifi Configuration Page </title>  \n"
    "<style>   \n"
    "Body {  \n"
    "  font-family: Calibri, Helvetica, sans-serif;  \n"
    "  background-color: lime-green;  \n"
    "}  \n"
    "button {   \n"
    "       background-color: #4CAF50;   \n"
    "       width: 100%;  \n"
    "        color: white;   \n"
    "        padding: 15px;   \n"
    "        margin: 10px 0px;   \n"
    "        border: none;   \n"
    "        cursor: pointer;   \n"
    "         }   \n"
    " form {   \n"
    "        border: 3px solid #f1f1f1;   \n"
    "    }   \n"
    " input[type=text], input[type=password] {   \n"
    "        width: 100%;   \n"
    "        margin: 8px 0;  \n"
    "        padding: 12px 20px;   \n"
    "        display: inline-block;   \n"
    "        border: 2px solid green;   \n"
    "        box-sizing: border-box;   \n"
    "    }  \n"
    " button:hover {   \n"
    "        opacity: 0.7;   \n"
    "    }   \n"
    "  .cancelbtn {   \n"
    "        width: auto;   \n"
    "        padding: 10px 18px;  \n"
    "        margin: 10px 5px;  \n"
    "    }   \n"
    "        \n"
    "     \n"
    " .container {   \n"
    "        padding: 25px;   \n"
    "        background-color: lightblue;  \n"
    "    }   \n"
    "</style>   \n"
    "</head>    \n"
    "<body>    \n"
    "    <center> <h1> WIFI Soft AP Configuration </h1> </center>   \n"
    "    <form mehtod = \"get\">  \n"
    "        <div class=\"container\">   \n"
    "            <label>WIFI SSID : </label>   \n"
    "            <input type=\"text\" placeholder=\"Enter SSID\" name=\"username\" required>  \n"
    "            <label>Password : </label>   \n"
    "            <input type=\"password\" placeholder=\"Enter Password\" name=\"password\" required>  \n"
    "            <button type=\"submit\">Connect</button>   \n"
    "            <button type=\"submit\">Scan</button>   \n"
    "            <button type=\"button\" class=\"cancelbtn\"> Cancel</button>   \n"
    "        </div>   \n"
    "    </form>     \n"
    "</body>     \n"
    "</html>  ";
#endif